- name: Install Node exporter
  hosts: node_exporter
  become: yes

  roles:
    - node-exporter
    - node_app

  # ansible-galaxy role init roles/node-exporter
  # ansible-galaxy role init roles/node_app