---
# tasks file for roles/node-exporter

- name: Install required packages
  yum:
    name: tar
    state: present

- name: Create User Node Exporter
  user:
    name: node_exporter
    shell: /sbin/nologin

- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract  Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt
    remote_src: yes

- name: Copy Binary
  copy:
    src: /opt/node_exporter-1.10.2.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '755'
    remote_src: yes

- name: Create Systemd service
  template: 
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service 

- name: Reload systemd
  command: systemctl daemon-reexec

- name: Start Node Exporter
  service: 
    name: node_exporter
    state: started
    enabled: yes
